import './KeyMetrics.css';
import ChartBarIcon from '../icons/chart-bar-solid.svg';
import UsersIcon from '../icons/user-solid.svg';
import DollarSignIcon from '../icons/dollar-sign-solid.svg';

const KeyMetrics = () => {
  return (
    <section id="key-metrics">
      <h2>Key Metrics</h2>
      <div className="m-container">
        <div className="metric card">
          <img src={ChartBarIcon} alt="Chart Bar Icon" className="icon" />
          <div className="text">
            <h3>Sales Growth</h3>
            <p>Monitor your sales performance over time and track your business growth.</p>
          </div>
        </div>
        <div className="metric card">
          <img src={UsersIcon} alt="Users Icon" className="icon" />
          <div className="text">
            <h3>Customer Engagement</h3>
            <p>Understand how engaged your customers are with your products or services.</p>
          </div>
        </div>
        <div className="metric card">
          <img src={DollarSignIcon} alt="Dollar Sign Icon" className="icon" />
          <div className="text">
            <h3>Revenue Increase</h3>
            <p>Track the increase in revenue generated by your business operations.</p>
          </div>
        </div>
      </div>
    </section>
  );
};

export default KeyMetrics;
